title: head in the cloud
author: zelaskov
theme: minima
email: marcinzelaskov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  just unimportant stuff

# social links
github_username:  zelaskov
linkedin_username: marcinzelaskov

show_excerpts: true # set to false to remove excerpts on the homepage
google_analytics: G-XFEW07SB1E
