title: head in the cloud
author: zelaskov
email: marcinzelaskov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  just unimportant stuff

# social links
github_username:  zelaskov

show_excerpts: true # set to false to remove excerpts on the homepage
